### ISSUE TITLE
Note Capitalization

### ISSUE THREAD

**Issue by tgrosinger** [levirs565/obsidian-dendron-tree#3]
It looks like the tree view is changing the capitalization of my note titles. For example, if a file is named `Ledger.TUI`, it will be displayed in the tree as `Ledger › Tui`

**Comment by levirs565** [comment]
I have fixed this bug in latest release. Please update your Dendron Tree plugin to [v1.1.1](https://github.com/levirs565/obsidian-dendron-tree/releases/tag/1.1.1). Please close this issue if bug is fixed.

**Comment by tgrosinger** [comment]
This is working now, thank you.
