### ISSUE TITLE
Expansion chevrons don't rotate

### ISSUE THREAD

**Issue by tgrosinger** [levirs565/obsidian-dendron-tree#4]
The chevrons indicating that the tree can be expanded to reveal another layer are always pointed down. I would expect them to be pointing to the right until they are clicked to expand.

**Comment by levirs565** [comment]
Please update your obsidian application. 

What is your obsidian application version?

**Comment by levirs565** [comment]
I have fixed this bug in latest release. Please update your Dendron Tree plugin to [v1.1.1](https://github.com/levirs565/obsidian-dendron-tree/releases/tag/1.1.1).
