### ISSUE TITLE
See also - Crumbs Plugin

### ISSUE THREAD

**Issue by tgrosinger** [levirs565/obsidian-dendron-tree#5]
Hey @levirs565, this plugin is great. Thank you for making it. I've never used Dendron, but I use the dot-denoted-hierarchy. I created the [Crumbs plugin](https://github.com/tgrosinger/crumbs-obsidian/) to support my workflow, but there are definitely things missing that your plugin adds.

Do you have plans to add other functionality, such as moving an entire sub-tree?

**Comment by levirs565** [comment]
I will add another functionality when I have free time. What functionality do you want?

**Comment by tgrosinger** [comment]
I don't have any particular functionality in mind. I just wanted to say thanks and let you know about my somewhat related plugin.
