### ISSUE TITLE
Add Reveal in Dendron Tree to file menu

### ISSUE THREAD

**Issue by tgrosinger** [levirs565/obsidian-dendron-tree#6]
Just like how you can reveal the current file in the built-in navigation, it would be helpful if you can reveal it in the Dendron Tree plugin instead.

Alternatively, you could also make the Dendron Tree always focus on the active file, just like how the Explore sidebar in VS-Code functions.

![Screenshot 2023-06-01 124214](https://github.com/levirs565/obsidian-dendron-tree/assets/597386/dff14519-16db-4538-afe5-ee8c9a143a63)

Thanks!

**Comment by levirs565** [comment]
I have a question while implementing this feature. When running "Reveal in Dendron Tree", do you think it is better to use scroll with animation (smooth scrolling) or without animation?
This feature have been implemented in latest commit but not released yet. Currently "Reveal in Dendron Tree" will smooth scroll into target note. In comparison, VS Code uses scroll without animation.

**Comment by tgrosinger** [comment]
Wow, thanks for adding this so quickly!

I would probably try to maintain consistency with the built-in file explorer view. It looks like it jumps directly to the note with no scrolling.

**Comment by levirs565** [comment]
Newer version of Dendron Tree is released. This release bring "Reveal in Dendron Tree" to file menu and automatically reveal file in tree when opening file.
