### ISSUE TITLE
Feature Request: Sort hierarchy based on title in metadata instead of file name

### ISSUE THREAD

**Issue by Rudtrack** [levirs565/obsidian-dendron-tree#9]
Hi! Amazing plugin, been looking for something like this since Dendron paused development.

I would love the ability to sort the hierarchy based on the title in the metadata/YAML instead of only file title. I've attached some pictures to show what I mean:

**Obsidian with this plugin**
![image](https://github.com/levirs565/obsidian-dendron-tree/assets/47916223/47f38568-11b9-4f7a-931f-fb791c4dcae7)

**Dendron in VSCode**
![image](https://github.com/levirs565/obsidian-dendron-tree/assets/47916223/13b23711-8d11-448d-8257-c98c5aa53d0d)

**Comment by levirs565** [comment]
I have added this feature into latest Dendron Tree release. You can update your plugin to v1.3.0. If your problem is fixed, please close this issue.
